package com.liferay.portal.model;

/*-
 * #%L
 * Liferay Authentication Client with Web Services
 * %%
 * Copyright (C) 2013 - 2025 BiiT Sourcing Solutions S.L.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

public enum ActionKey {

    ACCESS("ACCESS"),

    ACCESS_IN_CONTROL_PANEL("ACCESS_IN_CONTROL_PANEL"),

    ADD_ARTICLE("ADD_ARTICLE"),

    ADD_ATTACHMENT("ADD_ATTACHMENT"),

    ADD_CATEGORY("ADD_CATEGORY"),

    ADD_COMMUNITY("ADD_COMMUNITY"),

    ADD_COUPON("ADD_COUPON"),

    ADD_DEFINITION("ADD_DEFINITION"),

    ADD_DISCUSSION("ADD_DISCUSSION"),

    ADD_DISPLAY_STYLE("ADD_DISPLAY_STYLE"),

    ADD_DOCUMENT("ADD_DOCUMENT"),

    ADD_DOCUMENT_TYPE("ADD_DOCUMENT_TYPE"),

    ADD_ENTRY("ADD_ENTRY"),

    ADD_EVENT("ADD_EVENT"),

    ADD_EXPANDO("ADD_EXPANDO"),

    ADD_FEED("ADD_FEED"),

    ADD_FILE("ADD_FILE"),

    ADD_FOLDER("ADD_FOLDER"),

    ADD_FRAMEWORK_VERSION("ADD_FRAMEWORK_VERSION"),

    ADD_GENERAL_ANNOUNCEMENTS("ADD_GENERAL_ANNOUNCEMENTS"),

    ADD_IMAGE("ADD_IMAGE"),

    ADD_INSTANCE("ADD_INSTANCE"),

    ADD_ITEM("ADD_ITEM"),

    ADD_LAYOUT("ADD_LAYOUT"),

    ADD_LAYOUT_BRANCH("ADD_LAYOUT_BRANCH"),

    ADD_LAYOUT_PROTOTYPE("ADD_LAYOUT_PROTOTYPE"),

    ADD_LAYOUT_SET_BRANCH("ADD_LAYOUT_SET_BRANCH"),

    ADD_LAYOUT_SET_PROTOTYPE("ADD_LAYOUT_SET_PROTOTYPE"),

    ADD_LICENSE("ADD_LICENSE"),

    ADD_MESSAGE("ADD_MESSAGE"),

    ADD_NODE("ADD_NODE"),

    ADD_ORGANIZATION("ADD_ORGANIZATION"),

    ADD_PAGE("ADD_PAGE"),

    ADD_PASSWORD_POLICY("ADD_PASSWORD_POLICY"),

    ADD_PORTLET_DISPLAY_TEMPLATE("ADD_PORTLET_DISPLAY_TEMPLATE"),

    ADD_PRODUCT_ENTRY("ADD_PRODUCT_ENTRY"),

    ADD_PRODUCT_VERSION("ADD_PRODUCT_VERSION"),

    ADD_QUESTION("ADD_QUESTION"),

    ADD_REPOSITORY("ADD_REPOSITORY"),

    ADD_ROLE("ADD_ROLE"),

    ADD_RULE_GROUP("ADD_RULE_GROUP"),

    ADD_RULE_GROUP_INSTANCE("ADD_RULE_GROUP_INSTANCE"),

    ADD_SHORTCUT("ADD_SHORTCUT"),

    ADD_SUBCATEGORY("ADD_SUBCATEGORY"),

    ADD_SUBFOLDER("ADD_SUBFOLDER"),

    ADD_TAG("ADD_TAG"),

    ADD_TO_PAGE("ADD_TO_PAGE"),

    ADD_TOPIC("ADD_TOPIC"),

    ADD_USER("ADD_USER"),

    ADD_USER_GROUP("ADD_USER_GROUP"),

    ADD_VOCABULARY("ADD_VOCABULARY"),

    ADD_VOTE("ADD_VOTE"),

    ASSIGN_MEMBERS("ASSIGN_MEMBERS"),

    ASSIGN_USER_ROLES("ASSIGN_USER_ROLES"),

    BAN_USER("BAN_USER"),

    CONFIGURATION("CONFIGURATION"),

    CONFIGURE_PORTLETS("CONFIGURE_PORTLETS"),

    CUSTOMIZE("CUSTOMIZE"),

    DEFINE_PERMISSIONS("DEFINE_PERMISSIONS"),

    DELEGATE("DELEGATE"),

    DELETE("DELETE"),

    DELETE_DISCUSSION("DELETE_DISCUSSION"),

    DELETE_LAYOUT_BRANCH("DELETE_LAYOUT_BRANCH"),

    DELETE_USER("DELETE_USER"),

    EXPIRE("EXPIRE"),

    EXPORT_ALL_EVENTS("EXPORT_ALL_EVENTS"),

    EXPORT_IMPORT_LAYOUTS("EXPORT_IMPORT_LAYOUTS"),

    EXPORT_IMPORT_PORTLET_INFO("EXPORT_IMPORT_PORTLET_INFO"),

    EXPORT_USER("EXPORT_USER"),

    GUEST_PREFERENCES("GUEST_PREFERENCES"),

    HELP("HELP"),

    IMPERSONATE("IMPERSONATE"),

    IMPORT("IMPORT"),

    LOCK_THREAD("LOCK_THREAD"),

    MANAGE("MANAGE"),

    MANAGE_ANNOUNCEMENTS("MANAGE_ANNOUNCEMENTS"),

    MANAGE_ARCHIVED_SETUPS("MANAGE_ARCHIVED_SETUPS"),

    MANAGE_COUPONS("MANAGE_COUPONS"),

    MANAGE_LAYOUTS("MANAGE_LAYOUTS"),

    MANAGE_ORDERS("MANAGE_ORDERS"),

    MANAGE_STAGING("MANAGE_STAGING"),

    MANAGE_SUBGROUPS("MANAGE_SUBGROUPS"),

    MANAGE_SUBORGANIZATIONS("MANAGE_SUBORGANIZATIONS"),

    MANAGE_TEAMS("MANAGE_TEAMS"),

    MANAGE_USERS("MANAGE_USERS"),

    MERGE("MERGE"),

    MOVE_THREAD("MOVE_THREAD"),

    OVERRIDE_CHECKOUT("OVERRIDE_CHECKOUT"),

    PERMISSIONS("PERMISSIONS"),

    PERMISSIONS_USER("PERMISSIONS_USER"),

    PREFERENCES("PREFERENCES"),

    PREVIEW_IN_DEVICE("PREVIEW_IN_DEVICE"),

    PRINT("PRINT"),

    PUBLISH_PORTLET_INFO("PUBLISH_PORTLET_INFO"),

    PUBLISH_STAGING("PUBLISH_STAGING"),

    REPLY_TO_MESSAGE("REPLY_TO_MESSAGE"),

    SIGNAL("SIGNAL"),

    SUBMIT("SUBMIT"),

    SUBSCRIBE("SUBSCRIBE"),

    UNLINK_LAYOUT_SET_PROTOTYPE("UNLINK_LAYOUT_SET_PROTOTYPE"),

    UPDATE("UPDATE"),

    UPDATE_DISCUSSION("UPDATE_DISCUSSION"),

    UPDATE_THREAD_PRIORITY("UPDATE_THREAD_PRIORITY"),

    UPDATE_USER("UPDATE_USER"),

    VIEW("VIEW"),

    VIEW_CONTROL_PANEL("VIEW_CONTROL_PANEL"),

    VIEW_MEMBERS("VIEW_MEMBERS"),

    VIEW_SITE_ADMINISTRATION("VIEW_SITE_ADMINISTRATION"),

    VIEW_STAGING("VIEW_STAGING"),

    VIEW_TREE("VIEW_TREE"),

    VIEW_USER("VIEW_USER");

    private String liferayTag;

    ActionKey(String liferayTag) {
        this.liferayTag = liferayTag;
    }

    public String getLiferayTag() {
        return liferayTag;
    }

}
